import 'package:flutter/material.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedMeninfWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedRectangle22Widget2.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedCuadroWidget1.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedVectorWidget41.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedVectorWidget40.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedKrQkCVZO1BIWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedBoletoa2Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedBoletodeidaaGuadalajaraWidget1.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedboletoidawidget/generated/GeneratedRegresar1Widget.dart';

/* Frame Boleto-ida
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBoletoidaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 16, 13, 123),
                ),
              ),
              Positioned(
                left: -275.0,
                top: -605.0,
                right: null,
                bottom: null,
                width: 1080.0,
                height: 1920.0,
                child: GeneratedKrQkCVZO1BIWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 414.0,
                child: GeneratedBoletoa2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 117.0,
                child: GeneratedMeninfWidget4(),
              ),
              Positioned(
                left: 15.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 328.0,
                child: GeneratedCuadroWidget1(),
              ),
              Positioned(
                left: 39.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 51.0,
                child: GeneratedRectangle22Widget2(),
              ),
              Positioned(
                left: 88.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 25.0,
                child: GeneratedBoletodeidaaGuadalajaraWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.038736297312566045;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      16.036827087402344;

                  double percentHeight = 0.025669642857142856;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 23.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8164251207729468,
                        translateY:
                            constraints.maxHeight * 0.056919642857142856,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget40())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.038736297312566045;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      16.036827087402344;

                  double percentHeight = 0.025669642857142856;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 23.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.14251207729468598,
                        translateY:
                            constraints.maxHeight * 0.056919642857142856,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget41())
                  ]);
                }),
              ),
              Positioned(
                left: 129.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 43.0,
                child: GeneratedRegresar1Widget(),
              )
            ]),
      ),
    ));
  }
}
