import 'package:flutter/material.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedrecuperacionwidget/generated/GeneratedInputWidget2.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedrecuperacionwidget/generated/GeneratedIngresatunumerodecelularWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedrecuperacionwidget/generated/GeneratedSiguienteWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedrecuperacionwidget/generated/GeneratedSeenviaraunpinWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedrecuperacionwidget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedrecuperacionwidget/generated/GeneratedUpsssOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedrecuperacionwidget/generated/GeneratedSigno1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedrecuperacionwidget/generated/GeneratedInputWidget1.dart';

/* Frame Recuperacion 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRecuperacionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -45.0,
                right: null,
                bottom: null,
                width: 878.0,
                height: 986.0,
                child: GeneratedSigno1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 500.0,
                child: GeneratedRectangle2Widget3(),
              ),
              Positioned(
                left: 67.0,
                top: null,
                right: null,
                bottom: null,
                width: 313.0,
                height: 30.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -190.00,
                    z: 0,
                    child: GeneratedIngresatunumerodecelularWidget()),
              ),
              Positioned(
                left: 47.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 137.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 19.0,
                child: GeneratedSeenviaraunpinWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 361.0,
                height: 94.0,
                child: TransformHelper.translate(
                    x: 1.50,
                    y: -262.00,
                    z: 0,
                    child: GeneratedUpsssOlvidastetucontraseaWidget()),
              ),
              Positioned(
                left: 47.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget2(),
              ),
              Positioned(
                left: 137.0,
                top: 692.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 50.0,
                child: GeneratedSiguienteWidget(),
              )
            ]),
      ),
    ));
  }
}
