import 'package:flutter/material.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedajusteswidget14/generated/GeneratedEditarlainformacinWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedajusteswidget14/generated/GeneratedCerrarWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedajusteswidget14/generated/GeneratedAvionmosaico1Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedajusteswidget14/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedajusteswidget14/generated/GeneratedMeninfWidget7.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedajusteswidget14/generated/GeneratedUserWidget17.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 16, 13, 123),
                ),
              ),
              Positioned(
                left: -95.0,
                top: -42.0,
                right: null,
                bottom: null,
                width: 722.0,
                height: 1153.0,
                child: GeneratedAvionmosaico1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 117.0,
                child: GeneratedMeninfWidget7(),
              ),
              Positioned(
                left: 75.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 64.0,
                child: GeneratedCerrarWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 555.0,
                child: GeneratedUserWidget17(),
              ),
              Positioned(
                left: 24.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 65.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 70.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 37.0,
                child: GeneratedEditarlainformacinWidget(),
              )
            ]),
      ),
    ));
  }
}
