import 'package:flutter/material.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedaddwidget2/generated/GeneratedI0fCUofGjV8Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedaddwidget2/generated/GeneratedMeninfWidget2.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedaddwidget2/generated/GeneratedAgregarWidget.dart';

/* Frame Add
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 16, 13, 123),
                ),
              ),
              Positioned(
                left: -35.0,
                top: -38.0,
                right: null,
                bottom: null,
                width: 505.0,
                height: 920.0,
                child: GeneratedI0fCUofGjV8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 117.0,
                child: GeneratedMeninfWidget2(),
              ),
              Positioned(
                left: 23.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 647.0,
                child: GeneratedAgregarWidget(),
              )
            ]),
      ),
    ));
  }
}
