import 'package:flutter/material.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedvueloswidget/generated/GeneratedJuarezWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedvueloswidget/generated/GeneratedGuadaWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedvueloswidget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedvueloswidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedvueloswidget/generated/GeneratedTitleWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedvueloswidget/generated/GeneratedViaje1Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedvueloswidget/generated/GeneratedMeninfWidget1.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedvueloswidget/generated/GeneratedRegresoWidget.dart';

/* Frame Vuelos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVuelosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 16, 13, 123),
                ),
              ),
              Positioned(
                left: -20.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 434.0,
                height: 814.0,
                child: GeneratedViaje1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 117.0,
                child: GeneratedMeninfWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 173.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 81.0,
                child: GeneratedTitleWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 426.0,
                child: GeneratedJuarezWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 51.0,
                child: GeneratedGuadaWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 43.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 131.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 43.0,
                child: GeneratedRegresoWidget(),
              )
            ]),
      ),
    ));
  }
}
