import 'package:flutter/material.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedmeninfwidget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedmeninfwidget/generated/GeneratedAddWidget.dart';

/* Component Menú-inf
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMeninfWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 117.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight * 0.811965811965812;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.18803418803418803,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedFrame3Widget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.16908212560386474;

                final double height =
                    constraints.maxHeight * 0.5982905982905983;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.41545893719806765,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedAddWidget(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
