import 'package:flutter/material.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedusuariowidget6/generated/GeneratedBienvenidaKarlaWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedusuariowidget6/generated/GeneratedUserWidget14.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedusuariowidget6/generated/GeneratedPCcGpVsOHooWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedusuariowidget6/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedusuariowidget6/generated/GeneratedMeninfWidget6.dart';

/* Frame Usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUsuarioWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 16, 13, 123),
                ),
              ),
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/15d5f28df5e6d60778f58c1e0d48383241adb551.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 414.0,
                  height: 896.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: -80.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 504.0,
                height: 924.0,
                child: GeneratedPCcGpVsOHooWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 117.0,
                child: GeneratedMeninfWidget6(),
              ),
              Positioned(
                left: 22.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 371.0,
                height: 620.0,
                child: GeneratedUserWidget14(),
              ),
              Positioned(
                left: 27.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 65.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedBienvenidaKarlaWidget(),
              )
            ]),
      ),
    ));
  }
}
