import 'package:flutter/material.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedloginwidget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedloginwidget/generated/GeneratedImagenWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedloginwidget/generated/GeneratedTitulosubWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedloginwidget/generated/GeneratedBoletoWidget12.dart';
import 'package:flutterapp/aeropuerto_figmaapp/generatedloginwidget/generated/GeneratedContraseaWidget.dart';

/* Frame LogIn
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogInWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 652.0,
                child: GeneratedImagenWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 500.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 110.0,
                child: GeneratedTitulosubWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBoletoWidget12(),
              ),
              Positioned(
                left: 37.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedContraseaWidget(),
              ),
              Positioned(
                left: 67.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 26.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 788.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 95.0,
                child: GeneratedBotonWidget(),
              )
            ]),
      ),
    ));
  }
}
